### ISSUE TITLE
Blacklisted players not working with Firefox

### ISSUE THREAD

**Issue by internauta2000** [sakithb/media-controls#215]
Blacklisted players not working with Firefox after upgrading to version 2.2.0

Manjaro Linux with Gnome 48.2

I've disabled all installed extensions and the error persists.

<img width="1056" height="738" alt="Image" src="https://github.com/user-attachments/assets/087e504e-4a6a-44bc-b04f-746b9cf8c636" />

**Comment by Bjufen** [comment]
Hey! I had a similar issue.
Whenever I added blacklisted players, they would not work, and when I closed and opened the settings again, they were gone and I had to add them all over again.

I checked the errors: I had a TypeError in helpers/prefs/BlacklistedPlayers.js
The issue was, there was no undefined check for the apps that were loaded, so, if you add an undefined ( if (!app) continue), the issue should be fixed.
You should also reset the key blacklistedPlayers with this command:
gsettings reset org.gnome.shell.extensions.mediacontrols blacklisted-players

Then, restart your shell and it should work fine!

That is, if we had the same issue

**Comment by Bjufen** [comment]
> if you add an undefined ( if (!app) continue), the issue should be fixed.

You might need to recompile your schema (I did just to be safe)

**Comment by Bjufen** [comment]
> The issue was, there was no undefined check for the apps that were loaded, so, if you add an undefined ( if (!app) continue), the issue should be fixed.
But that's pretty much it.
I just remembered I already posted the spot where I changed something
It is in the file helpers/prefs/BlacklistedPlayers.js

There is a for loop that iterates through all the apps you have blacklisted. However it does not account (at least that's my thought) for blacklisted apps that are no longer on the system.

The change is really simple:
```

for (const player of this.players) {
            const row = new Adw.ActionRow();
            const app = apps.find((app) => app.get_id() === player);
//ADD A GUARD CLAUSE HERE
if (!app) {
    continue;
}
            row.title = app.get_display_name();

```


Please excuse any indentation errors. I am writing this on my phone😅

**Comment by realDayaa** [comment]
The merge request still didn't resolve the original problem of Firefox being ignored, unfortunately.  
Maybe this has to do with the exact application ID, as Firefox in the extensions is shown as "org.mozilla.firefox.desktop"
whereas the ID of Firefox when open is only "org.mozilla.firefox"

See https://github.com/sakithb/media-controls/issues/223#issuecomment-3241584413
